const startingPoints={
  starting:{title:'Start with one useful pilot.',steps:['Choose a repetitive task your team already understands, such as drafting answers to common questions.','Gather a few approved examples and name the person who will check the output.','Try it with sample information; compare the time spent and corrections needed before expanding.']},
  scattered:{title:'Make the information easier to use.',steps:['Choose one process and list the apps, documents and people it touches.','Pick the source of truth, remove outdated instructions and write down the steps.','Check access and connection options, then test one handoff before connecting more systems.']},
  team:{title:'Make your team part of the pilot.',steps:['Ask the people doing the work which repetitive task they would most like help with.','Practice on familiar examples and agree what AI may draft, what people must check and when to escalate.','Choose a team champion, review feedback and measure errors as well as time saved.']},
  growing:{title:'Connect what is already working.',steps:['List the AI tools and workflows already in use, including their owners and recurring costs.','Look for duplicate work or missing handoffs between customer enquiries, CRM, scheduling and billing.','Test one connection with clear permissions, an exception owner and a way to pause it.']}
};
const select=document.querySelector('#readiness-stage'),output=document.querySelector('#readiness-result');
function render(){const point=startingPoints[select.value];output.querySelector('h4').textContent=point.title;output.querySelector('ol').replaceChildren(...point.steps.map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));}
select.addEventListener('change',render);
document.querySelectorAll('[data-show-workflow]').forEach(button=>button.addEventListener('click',()=>{document.querySelector(`button[data-workflow="${button.dataset.showWorkflow}"]`).click();document.querySelector('#workflow-stage').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});document.querySelector('#workflow-title').focus({preventScroll:true});}));
document.querySelector('#readiness-download').hidden=false;
document.querySelector('#readiness-download').addEventListener('click',()=>{const p=startingPoints[select.value];const content=`SOVEREIGN HQ — YOUR AI STARTING POINT\n\n${p.title}\n\n${p.steps.map((s,i)=>`${i+1}. ${s}`).join('\n')}\n\nBefore you start: agree the task owner, approved information, review points and success measure. For healthcare workflows, scope data access and approved systems before using patient information.\n\nThis is a planning guide, not a readiness certification. Prepared locally; nothing has been submitted or booked.\n`;const u=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='sovereign-ai-starting-point.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});
